services:
  - type: web
    name: pixel-positions
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:m0TatBZduRyTlnu+3JcQzs8fKDm/cr4Fj8VBOh6cFLk=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
    ports:
      - containerPort: 10000
        protocol: HTTP
