services:

* type: web
  name: pixel-positions
  env: docker
  plan: free
  dockerfilePath: ./Dockerfile
  autoDeploy: true
  branch: main
  envVars:

  * key: APP_ENV
    value: production
  * key: APP_DEBUG
    value: false
  * key: APP_URL
    value: [https://pixel-positions-laracasts-course-final.onrender.com](https://pixel-positions-laracasts-course-final.onrender.com)
  * key: APP_KEY
    value: base64:SYEcVk+YjGLWmyUplBSRFH26sYMK6OI1NxlGj6vlDkQ=
  * key: DB_CONNECTION
    value: sqlite
  * key: DB_DATABASE
    value: /var/www/html/database/database.sqlite
    ports:
  * containerPort: 10000
    protocol: HTTP
